//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstRestoran.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorbaTbl
    {
        public int CorbaID { get; set; }
        public string CorbaAdi { get; set; }
        public decimal CorbaFiyat { get; set; }
        public YemekTur corbaTur { get; set; }

        public override string ToString()
        {
            return $"{CorbaAdi} {corbaTur} {CorbaFiyat}";
        }
    }
}
