//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstRestoran.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KebabTbl
    {
        public int KebabId { get; set; }
        public string KebabAdi { get; set; }
        public decimal KebabFiyat { get; set; }
        public YemekTur kebabTur { get; set; }

        public override string ToString()
        {
            return $"{KebabAdi}  {kebabTur} {KebabFiyat}";
        }
    }
}
