//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstRestoran.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestoranDbEntities : DbContext
    {
        public RestoranDbEntities()
            : base("name=RestoranDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CorbaTbl> CorbaTbls { get; set; }
        public virtual DbSet<KebabTbl> KebabTbls { get; set; }
        public virtual DbSet<SalataTbl> SalataTbls { get; set; }
    }
}
