//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstRestoran.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalataTbl
    {
        public int SalataID { get; set; }
        public string SalataAdi { get; set; }
        public decimal SalataFiyat { get; set; }
        public YemekTur salataTur { get; set; }

        public override string ToString()
        {
            return $"{SalataAdi}  {salataTur} {SalataFiyat}";
        }
    }
}
